### ISSUE TITLE
UnboundLocalError: local variable 'contains_faces' referenced before assignment

### ISSUE THREAD

**Issue by jonatas-lima** [redhuntlabs/Octopii#12]
**Describe the bug**
When running the tool on a directory without images or PDF files, an `UnboundLocalError` is raised because the variable `contains_faces` has not been initialized. I believe that adding `contains_faces = 0` at the beginning of the `search_pii(file_path)` function will solve the issue.

**To Reproduce**
1. Create a directory `dir` only with text files
2. Run `python3 octopii.py dir/`

**Expected behavior**
Octopii runs successfully

**Comment by owais-redhunt** [comment]
Thanks. Fixed in #13
