### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by MichaelCade** [redhuntlabs/Octopii#19]
**Is your feature request related to a problem? Please describe.**
I have a use case which is where I want to scan through backup files with Octopii on an SMB share. The capability works for this but there are some additional steps in that I have to make sure my Linux machine has access to the SMB share or the Backup file in question. If we could enable this to work on Windows as well this would help my use case. 

**Describe the solution you'd like**
I am not sure how big this lift is, more than happy to help where possible. I have added the errors below that I see after confirming that the dependencies for windows are available. 

It is not the end of the world but being able to run this from a Windows box would be better than having a dedicated Linux box for this task. 

**Additional context**
When I run on Windows where I have already installed Tesseract I get the following: 

```
 Octopii  python .\octopii.py .\dummy-pii\
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Octopii\octopii.py", line 123, in <module>
    rules=text_utils.get_regexes()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Octopii\text_utils.py", line 52, in get_regexes
    _rules = json.load(json_file)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3062: character maps to <undefined>
```

**Comment by 0x4f53** [comment]
Hey Michael, I believe this issue can be solved by dockerizing Octopii as opposed to making separate binaries for Windows (explained in issue #6). We may do this in the future, when we update Octopii, so stay tuned!
