### ISSUE TITLE
python3 octopii.py Traceback (most recent call last):   File "/home/kali/Octopii/octopii.py", line 33, in <module>     from keras.models import load_model ModuleNotFoundError: No module named 'keras'

### ISSUE THREAD

**Issue by kreds32122** [redhuntlabs/Octopii#2]

**Comment by owais-redhunt** [comment]
Keras is a dependency needed to run the tool. Did you install it and all the other required dependencies? Please refer to the [README's "Usage" section](https://github.com/redhuntlabs/Octopii/blob/master/README.md#Usage) on how to do this.
