### ISSUE TITLE
Feature request: portable app

### ISSUE THREAD

**Issue by scythe000** [redhuntlabs/Octopii#6]
Would there be an easy way to make this portable so I could toss it on a thumb drive and run it on a random workstation?

**Comment by owais-redhunt** [comment]
Hey there. This app has system-level package requirements such as pytesseract which needs to be installed via the system's package manager. It also needs to download the latest NLTK files. So a portable app isn't in the books so far. Plus, this tool is meant to be a simple CLI tool. Dockerization, however, is possible, so there's that...
